version: '3.4'

services:
  sit3237372023t1prac5d:
    image: sit3237372023t1prac5d
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
